# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b4361ed7-05ec-4933-b28d-ee09f0e084a2";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/CEB3-562A";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/mapper/luks-d7ff8bc2-b352-4622-a622-7f01c43e3314";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-d7ff8bc2-b352-4622-a622-7f01c43e3314".device = "/dev/disk/by-uuid/d7ff8bc2-b352-4622-a622-7f01c43e3314";

  swapDevices =
    [ { device = "/dev/disk/by-uuid/0b8e28a7-9d31-4f67-844d-493551603edb"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
